name: quiz_project
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+5

environment:
  sdk: ^3.7.2
dependencies:
  flutter:
    sdk: flutter
#  audioplayers: ^6.4.0
  url_launcher: ^6.3.1
  google_mobile_ads: ^6.0.0
#  advertising_id: ^2.7.1
  get_storage: ^2.1.1
  get: ^4.7.2
  share_plus: ^10.1.4

  cupertino_icons:
  logger:
#  google_fonts: ^6.2.1
  flutter_screenutil: ^5.9.3
  double_tap_to_exit: ^1.0.2
#  flutter_launcher_icons: ^0.14.3
#  flutter_native_splash: ^2.4.6
  http: ^1.3.0
  flutter_dotenv: ^5.2.1


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon/icon.png"

flutter_native_splash:
  image: assets/icon/icon.png
  color: "#000000"

flutter:
  uses-material-design: true
  generate: true  # Required for localization code generation

  assets:
    - assets/images/
    - assets/sounds/
    - assets/icon/
    - assets/lottie/
    - assets/data/quiz_ar.json
    - .env

  fonts:
    - family: NotoSansArabic
      fonts:
        - asset: assets/fonts/NotoSansArabic-Regular.ttf
        - asset: assets/fonts/NotoSansArabic-Bold.ttf
          weight: 700

    - family: IBMPlexSansArabic
      fonts:
        - asset: assets/fonts/ibm_plex/IBMPlexSansArabic-Bold.ttf
          weight: 700
