name: quiz_project
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.7.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  audioplayers:
  # Localization
  flutter_localizations:
    sdk: flutter
  intl:

  # Dialog dependencies
  share_plus:
  flutter_rating_bar:
  get:
  lottie:

  # UI
  cupertino_icons:
  flutter_gradient_colors:
  logger:
  google_fonts:
  flutter_screenutil:

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints:

flutter:
  uses-material-design: true
  generate: true  # Required for localization code generation

  assets:
    - assets/images/
    - assets/sounds/
    - assets/icons/
    - assets/lottie/
    - assets/data/quiz_ar.json

  fonts:
    - family: NotoSansArabic
      fonts:
        - asset: assets/fonts/NotoSansArabic-Regular.ttf
        - asset: assets/fonts/NotoSansArabic-Bold.ttf
          weight: 700

    - family: IBMPlexSansArabic
      fonts:
        - asset: assets/fonts/ibm_plex/IBMPlexSansArabic-Bold.ttf
          weight: 700
